# site settings
title: Agenda transparencia
email: prensa@ciudadanointeligente.org
email_subject: Prensa de agendatransparencia.org
description: Descubre y fiscaliza las 9 medidas de la AgendaTransparencia que estÃ¡n en riesgo de no ser ley.
baseurl: '//agendatransparencia.org' #example: '/agendatransparencia'
basedomain: agendatransparencia.org #ciudadanointeligente.github.io
analytics: 'UA-41822715-6'
texto_introductorio: Estas son las 12 propuestas para una
texto_que_remata:  Agenda de Transparencia para Argentina
texto_bajada: 'Enterate por quÃ© estas 12 polÃ­ticas de reforma son indispensables para avanzar hacia un sistema polÃ­tico mÃ¡s democrÃ¡tico.'

# social
hashtag: AgendaTransparencia
twitter_username: ciudadanoi
twitter_txt: 'ğŸ‘¦ğŸ‘§ğŸ‘¨ğŸ‘©ğŸ‘´ğŸ‘µ'

#support
support_enabled: false

# build settings
markdown: kramdown

#herokuapp
herokuapp: '//api.agendatransparencia.cl/proposals'

collections:
  cards:
    output: true
